### ISSUE TITLE
Feature request `isOpen`

### ISSUE THREAD

**Issue by darren131** [craftcms/store-hours#15]
Would be great to have a isOpen filter we could test against... Right now I'm doing this:
`{{ location.hours[now|date('w')].open < now and location.hours[now|date('w')].close > now ? 'Open now' : 'Closed' }}` which works but really messes up my template ;)

**Comment by brandonkelly** [comment]
As of the next release, Store Hours won’t have a firm grasp on whether the time is currently in an “open” window, as the actual time slots are going to be customizable (so no longer stuck with “Open” and “Close”). So we can’t implement this FR reliably.

So instead, I’ve at least made it easier to get to today’s hours, with a new `getToday()` function on the field data. So for example, your template code could be simplified to:

```twig
{{ location.hours.today.open < now and location.hours.today.close > now ? 'Open now' : 'Closed' }}
```

or:

```
{% set hours = location.hours.today %}
{{ hours.open < now and hours.close > now ? 'Open now' : 'Closed' }}
```
