### ISSUE TITLE
storeHours|length is always 7

### ISSUE THREAD

**Issue by pixeldeluxe** [craftcms/store-hours#16]
How do I Check is none of the storeHours is filled?
When you save the storeHours|length will be 7 instead of 0.

`{% if entry.storeHours|length %}
...
{% endif %}
`

**Comment by brandonkelly** [comment]
The field definitely isn’t optimized for this use case, but you could loop through each of the days and check their values:

```twig
{% set hasHours = false %}
{% for day in entry.storeHours %}
    {% if not hasHours and (day.open or day.close) %}
        {% set hasHours = true %}
    {% endif %}
{% endfor %}
```

Bonus points if you use the `{% break %}` tag provided by the [MN Twig Perversion](https://github.com/marionnewlevant/craft-twig_perversion) plugin:

```twig
{% set hasHours = false %}
{% for day in entry.storeHours %}
    {% if not hasHours and (day.open or day.close) %}
        {% set hasHours = true %}
        {% break %}
    {% endif %}
{% endfor %}
```
