### ISSUE TITLE
entry form - front end editing

### ISSUE THREAD

**Issue by CreateSean** [craftcms/store-hours#17]
I need to enable store managers to edit the store hours via a front end form, which I've got working for some basic fields. However I'm not sure how to get the store-hours field coded.

What is the best approach for this?

using the Craft 2.x version

**Comment by brandonkelly** [comment]
You would set it up exactly the same as the field in the Control Panel – just inspect it to see what the inputs should be named.

We are using a combination of [jQuery UI’s Datepicker](https://jqueryui.com/datepicker/) and [jquery.timepicker](http://jonthornton.github.io/jquery-timepicker/) in the CP.
