### ISSUE TITLE
Question: Grouping Days with Same Hours

### ISSUE THREAD

**Issue by mikestecker** [craftcms/store-hours#18]
Would it be possible to group days with the same open & close hours?

For example:

Monday - Thursday: 9:00am - 4:00pm
Friday: 9:00am - 6:00pm
Saturday - Sunday: 10:00am - 8:00pm

**Comment by brandonkelly** [comment]
Here’s one solution, from Stack Exchange: https://craftcms.stackexchange.com/a/18626/9

**Comment by mikestecker** [comment]
Wow, awesome thanks!
