### ISSUE TITLE
Saving shifts the time around

### ISSUE THREAD

**Issue by mikestecker** [craftcms/store-hours#21]
Craft version: 3.0.0-beta.34
Store Hours version: 2.0.5

Each time I click save on the entry, the time seems to shift by a number of hours. I'm not sure if it has something to do with the timezone.

After fixing the time, I checked the `content` table and it's stored as:

```json
[{"open":null,"close":null},{"open":"2017-11-12T08:00:00-05:00","close":"2017-11-12T16:00:00-05:00"},{"open":"2017-11-12T08:00:00-05:00","close":"2017-11-12T16:00:00-05:00"},{"open":"2017-11-12T08:00:00-05:00","close":"2017-11-12T16:00:00-05:00"},{"open":"2017-11-12T08:00:00-05:00","close":"2017-11-12T16:00:00-05:00"},{"open":"2017-11-12T08:00:00-05:00","close":"2017-11-12T16:00:00-05:00"},{"open":null,"close":null}]
```

Once I click `Save and continue editing` I see the times have changed on the UI and also in the database:

```json
[{"open":null,"close":null},{"open":"2017-11-12T13:00:00-05:00","close":"2017-11-12T21:00:00-05:00"},{"open":"2017-11-12T13:00:00-05:00","close":"2017-11-12T21:00:00-05:00"},{"open":"2017-11-12T13:00:00-05:00","close":"2017-11-12T21:00:00-05:00"},{"open":"2017-11-12T13:00:00-05:00","close":"2017-11-12T21:00:00-05:00"},{"open":"2017-11-12T13:00:00-05:00","close":"2017-11-12T21:00:00-05:00"},{"open":null,"close":null}]
```

This cycle repeats itself each time I click save.

For reference, the site's timezone in my case is set to UTC-5 Indianapolis however I am on Los Angeles time... not sure if that matters. This is happening on my local dev environment.

**Comment by brandonkelly** [comment]
That’s pretty bizarre, and not able to reproduce locally. Can you send in a support ticket from your dashboard (including the DB backup) so we can look into it on your site?

**Comment by mikestecker** [comment]
No problem, I just submitted it and put a link to this issue.

**Comment by mikestecker** [comment]
@brandonkelly you can close this issue. Turns out it was an issue with a plugin
