### ISSUE TITLE
Support multiple time inputs per day

### ISSUE THREAD

**Issue by Radiergummi** [craftcms/store-hours#22]
I'm currently working on a restaurant website. They have a time schedule that's pretty common in Germany:
- Closed on mondays
- Open from 10am to 5pm, closed from 5pm to 6:30pm, open from 6:30pm to 11pm on tuesdays, wednesdays, fridays and saturdays
- Open from 10am to 11pm on thursdays
- Open from 10am to 5pm on sundays

Currently, I solve this with a table input:

<table><th>Mo</th><th>Tu</th><th>We</th><th>Th</th><th>Fr</th><th>Sa</th><th>Su</th>
<tr><td></td><td>10-17</td><td>10-17</td><td>10-23</td><td>10-17</td><td>10-17</td><td>10-17</td></tr><tr><td></td><td>18:30-23</td><td>18:30-23</td><td></td><td>18:30-23</td><td>18:30-23</td><td></td></tr><tr><td colspan=7 align=center>+ Add row</td></tr></table>

Which works, but it feels bad having users type in the open hours as plain text instead of time. To turn this into usable JSON-LD data, I use the following Twig abomination:

```twig

{% set openingHours = [] %}
{% set monday =       [] %}
{% set tuesday =      [] %}
{% set wednesday =    [] %}
{% set thursday =     [] %}
{% set friday =       [] %}
{% set saturday =     [] %}
{% set sunday =       [] %}

{% for range in company.openingHours %}
  {% if range.Mo %}{% set monday    = monday    | merge( [ range.Mo ] ) %}{% endif %}
  {% if range.Tu %}{% set tuesday   = tuesday   | merge( [ range.Tu ] ) %}{% endif %}
  {% if range.We %}{% set wednesday = wednesday | merge( [ range.We ] ) %}{% endif %}
  {% if range.Th %}{% set thursday  = thursday  | merge( [ range.Th ] ) %}{% endif %}
  {% if range.Fr %}{% set friday    = friday    | merge( [ range.Fr ] ) %}{% endif %}
  {% if range.Sa %}{% set saturday  = saturday  | merge( [ range.Sa ] ) %}{% endif %}
  {% if range.Su %}{% set sunday    = sunday    | merge( [ range.Su ] ) %}{% endif %}
{% endfor %}

{% if monday %}{% set openingHours    = openingHours | merge( [ 'Mo ' ~ monday    | join(', ') ] ) %}{% endif %}
{% if tuesday %}{% set openingHours   = openingHours | merge( [ 'Tu ' ~ tuesday   | join(', ') ] ) %}{% endif %}
{% if wednesday %}{% set openingHours = openingHours | merge( [ 'We ' ~ wednesday | join(', ') ] ) %}{% endif %}
{% if thursday %}{% set openingHours  = openingHours | merge( [ 'Th ' ~ thursday  | join(', ') ] ) %}{% endif %}
{% if friday %}{% set openingHours    = openingHours | merge( [ 'Fr ' ~ friday    | join(', ') ] ) %}{% endif %}
{% if saturday %}{% set openingHours  = openingHours | merge( [ 'Sa ' ~ saturday  | join(', ') ] ) %}{% endif %}
{% if sunday %}{% set openingHours    = openingHours | merge( [ 'Su ' ~ sunday    | join(', ') ] ) %}{% endif %}

```

...which results in

```js
"openingHours": [
  "Tu 10:00-17:00, 18:30-23:00",
  "We 10:00-17:00, 18:30-23:00",
  "Th 10:00-23:00",
  "Fr 10:00-17:00, 18:30-23:00",
  "Sa 10:00-17:00, 18:30-23:00",
  "Su 10:00-17:00"
],
```

It would be awesome if we could get optional, additional hour columns 😊 
Would it be possible to make this work?

**Comment by brandonkelly** [comment]
@MakeilaLundy I started working on this in the `feature/time-slots` branch.

**Comment by Radiergummi** [comment]
Thank you so much @brandonkelly! I'll update the site next week. You guys are awesome!  🎉
