### ISSUE TITLE
Doesn't seem to work with the element API

### ISSUE THREAD

**Issue by buesing** [craftcms/store-hours#27]
I'm trying to set up this plugin and retrieving the data as JSON with the element API plugin, but only ever getting NULL although the fields are filled in. This is my endpoint:
```
    'stores.json' => function() {
      $langHandle = Craft::$app->request->getQueryParam('lang', 'en');
      return [
        'elementType' => Entry::class,
        'criteria' => [
          'section' => 'store',
          'site' => $langHandle,
        ],
        'paginate' => false,
        'cache' => $GLOBALS['cache'],
        'transformer' => function(Entry $entry) {
          var_dump($entry->openingHours);
          return [
            'title' => $entry->title,
            'slug' => $entry->slug,
            'id' => $entry->id,
            'openingDate' => $entry->openingDate ? $entry->openingDate->format("d.m.Y") : null,
            'closingDate' => $entry->closingDate ? $entry->closingDate->format("d.m.Y") : null,
            'openingHours' => $entry->openingHours,
          ];
        },
      ];
    },

```
Even var_dump'ing it always outputs null. Am I doing something wrong or is this a bug?

**Comment by brandonkelly** [comment]
You’re sure that the `id` coming back in the JSON is the same ID as the entry you’re adding store hours to in the Control Panel? (Take a look at the URL when editing the entry.)

**Comment by buesing** [comment]
Somebody else has been working on this project in the meantime and it works now. So I guess I must have done something wrong. Thanks!

**Comment by brandonkelly** [comment]
Great - glad they got it working  :)
