### ISSUE TITLE
Only show days that have time

### ISSUE THREAD

**Issue by mbanta88** [craftcms/store-hours#28]
My client's company is only open Mon-Fri. How can I make it so it only renders the days with times that are filled in instead of the entire week?

<img width="354" alt="screen shot 2018-06-25 at 4 14 55 pm" src="https://user-images.githubusercontent.com/22916757/41876293-ec882912-7892-11e8-835d-3dad8ae5930b.png">

<img width="491" alt="screen shot 2018-06-25 at 4 14 21 pm" src="https://user-images.githubusercontent.com/22916757/41876267-dfc1d214-7892-11e8-856c-fafd1002c478.png">

**Comment by brandonkelly** [comment]
You can wrap your `<tr ... />` code with this:

```twig
{% if dayHours.open or dayHours.close %}
    <tr ... />
{% endif %}
```
