### ISSUE TITLE
GraphQL Compatibility

### ISSUE THREAD

**Issue by chadclark** [craftcms/store-hours#36]
Being able to use the new baked-in GraphQL to query the Store Hours plugin would be very helpful.

**Comment by yusef-ho** [comment]
+1

**Comment by mvdesign** [comment]
I just ran into this, too. I was surprised that a first-party plugin would not show up in the schema. I'll look for another solution, but adding this functionality would be quite helpful.

**Comment by torgeirbeyer** [comment]
Is there any plan to support GraphQL in the future for this plugin?

**Comment by Rees1993** [comment]
Any update on this? Need it for a website I am currently building

**Comment by denisyilmaz** [comment]
@brandonkelly any plans to add GQL support for this plugin?

**Comment by bzin** [comment]
On a current project I am working the GraphQL support would be a HUGE help. Will this happen @brandonkelly ?! :)

**Comment by brandonkelly** [comment]
Store Hours 3.1.0 (Craft 4) and 4.0.0 (Craft 5) are out now with GraphQL support 🎉
