### ISSUE TITLE
FR: "now open"

### ISSUE THREAD

**Issue by bartrylant** [craftcms/store-hours#37]
### Description

Would be nice to have a template variable to check, to see if the store is open atm (not this day, but this very moment).

**Comment by thisisjamessmith** [comment]
Just wondering if anyone has managed to code this functionality manually?

**Comment by kculmback** [comment]
This is what we did as a workaround

```
{% set currentTime = date() %}
{% set todayHours = entry.<Field>.getToday() %}
{% set isOpen = date(todayHours.open|time) < currentTime and date(todayHours.close|time) > currentTime %}
```

**Comment by brandonkelly** [comment]
Just tagged Store Hours 4.1.0 with a new `getIsOpen()` method.

```twig
{% if entry.hours.isOpen %}
    <p>We’re open!</p>
{% endif %}
```
